### ISSUE TITLE
Stian Buch Larsen (lonix) Feedback

### ISSUE THREAD

**Issue by lonix** [githubschool/Nov-6#21]
I Just became a issue

**Comment by recet** [comment]
## Day 1 Review
Very good explanations and able to answer all questions. You know your stuff! It was a bit unfurtunate we did not allocate enough time for you to finish, but i have no negative feedback.

**Comment by recet** [comment]
## Day 2 Review
Learned something today aswell. Did not notice the squash and rebase options on GitHub, so it was nice you showed them. Like that you use proper names on stuff - so i can take notes about that 👍

**Comment by brianamarie** [comment]
[Recording](https://vimeo.com/242195585/a0fefb4226)

### Topic: [Introduction to GitHub](https://githubtraining.github.io/training-manual/GH4D/index), [Getting Ready for Class](https://githubtraining.github.io/training-manual/GH4D/01_getting_ready_for_class.html), & [Getting Started](https://githubtraining.github.io/training-manual/GH4D/02_getting_started.html)
- 👍 "things are in the way, so I'll need to move them" Great point - I'm glad that you're thinking about what the screen looks like to the participants! I can tell you've done this before. :wink:
- 👍 Demo strong even though you felt quite rushed.
- 👍 Pointing out what type of shell and editor you're using so it's clear what each participant is responsible for on their own machine

### Topic: [GitHub Flow](https://githubtraining.github.io/training-manual/GH4D/03_github_flow.html)
- When showing the browser, is there a way to bring the colors back to default? It might be easier to see on projectors, and the dark background being different from their own screen may confuse some people.
- 👍 Solid description of GitHub Flow, nice amount of time spent on this topic despite feeling rushed

### Topic: [Branching](https://githubtraining.github.io/training-manual/GH4D/04_branching_with_git.html)
- 👍 Smooth transition from GitHub flow into branching
- The part where you created a branch went very quickly. Was that a demo, or were you wanting others to follow along and do the same? If demo, how could you check to make sure they were able to create a branch?

### Topic: [Local Git Configs](https://githubtraining.github.io/training-manual/GH4D/05_local_git_configs.html)
- 👍 Accurate description
- I find it useful to show the image at this point
- Nice pace to make sure others were able to follow along, it was clear that they should be setting those configurations

### Topic: [Working Locally](https://githubtraining.github.io/training-manual/GH4D/06_working_locally.html)
- 👍 Easy to follow pace
- Ideally (if more time) don't forget to build in some checks with participants to make sure they're able to follow along 
- 👍 Favorite command = `git status` :100:
- You are using green for remote branches, but I recommend keeping the default red. If it's hard to see, maybe change the background to white. All of the slight visual differences can be quite confusing to those who are new to the command line. 
- 👍 Nice job mentioning that "checkout" means something different than it does in other version control systems. 

### General notes: 
- 👍 Very nice job! 
- Text windows being visible and similar to what participants have.
- Checking with participants to make sure they're keeping up and that your pacing is matching their skill level

**Comment by lonix** [comment]
Self evaluation:

+ I need more time to prep a "better enviorment" and im painfully aware of that, Thinking of seperate machine account all together to have a more clean and default experience. 
Deskin github!
+ Get some software for mousehighlighting (e.g. mousepose) 
+ Get Better at Acting (I Find it hard to pretend to teach)
+ Alternativly write a script to ensure to reset defaults ! and back without pushing changes to git (my config is in github https://github.com/lonix/dotfiles ) @brianamarie

**Comment by brianamarie** [comment]
> Get Better at Acting (I Find it hard to pretend to teach)

😂 I know what you mean. Teaching is a performance! I also think it's easier in person. 

For defaults, software, general presentation machine, some trainers have different user accounts on their machine for teaching. Some have considered VMs but it hasn't been as slick in practice. I use a script to prepare my machine, and I've been happy with it. Whatever you find that works, let me know, I'm always looking to improve my own workflow and recommend the best option to other trainers. 💯

**Comment by brianamarie** [comment]
[Recording](https://vimeo.com/242196255/5345865fd8)

### Topic: [Merging Pull Requests](https://githubtraining.github.io/training-manual/GH4D/09_merging_pull_requests.html)
- 👍 Off the bat, checking with participants to see if they're following along by asking if they could see your monitor. Sounds simple but it's very important!
- 👍 Reviewing where you left off so everyone starts on the same page
- 👍 Covering the types of merge when merging on GitHub.com. We generally don't cover this during the first few workflows on GitHub, but wait to address it after we've discussed what `squash` and `rebase` are. If we do cover it, we do it as you did it, which is briefly. :smile:
- Are others supposed to be following along? At this point it looks like a demo. Were we supposed to merge, too?
- 👍 When going back to the local environment, showing that the content from the pull request isn't shown on master is a nice way to connect the dots.
  - There was a good opportunity to check for participant understanding. Before you said we would need to pull, consider asking the participants _why_ the changes from the pull request aren't reflected locally. Even if it's an easy question, asking them will bring their attention back to the topic you are working on. They will be trying to think of an answer, even if it takes a while for someone to speak up.
- Accurate accounting of how to delete remote tracking branches.
  - This is a good opportunity to discuss the complexities of remote tracking branches in general. It's a difficult concept to grasp for many people new to Git, and it's very different from other version control systems.
- Make sure to cover `git branch -d` and `git branch --merged` as well

### Topic: [Local History](https://githubtraining.github.io/training-manual/GH4D/10_local_history.html)
- What's a log? When would it be used? Don't forget to explain the "why"
- Your default `git log --oneline` looks similar to `git log --oneline --decorate`.
- Uh oh! I hope that email isn't anything bad! :wink: Remember to mute notifications when presenting to a class.

### Topic: [Streamlining with Aliases](https://githubtraining.github.io/training-manual/GH4D/11_streamline_workflow_with_aliases.html)
- 👍 Covering the concepts well
- 👍 Covering how to see all configs and all aliases
- `git pull`  _is_  technically a [git command](https://git-scm.com/docs/git-pull), but you're right that it's _like_ an alias because it's a combination of `git fetch` and `git merge`. It would be good to cover that now!  

### Topic: [Resolving Merge Conflicts](https://githubtraining.github.io/training-manual/GH4D/12_resolving_merge_conflicts.html)
- 👍 Having a merge conflict set up gave you a quick place to jump into a Demo
- Why do merge conflicts happen? Make sure to explain the "why". I like to use the [visualization tool](git-school.github.io/visualizing-git) to show a merge, and ask students what they think would happen if there were changes on both branches to the same file?
- 👍 Explaining that we edit the file how we _want_ it to look, instead of having to select either one or keep both.
- 👍 Deciding to explain the merge conflict repositories

### General Feedback
- Very nice job!
- One way to improve is to make sure it's clear when participants are meant to be following along vs when they should just be watching.
- When in doubt, focus on the three main steps of:
  - Give instruction (Tell them what to do)
  - Observe (Are they doing what you told them to do?)
  - Give feedback (Tell them if they did the thing you asked them to do, in as specific of terms as possible)
- Without those three steps, it's not a class, but a demo.
- I can't wait to see more videos! :clap: :100:

**Comment by brianamarie** [comment]
Post test complete ✔️
